name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Pull Docker image
        run: sudo docker pull bilanox/devopes-ci-cd:latest
      - name: Delete Old docker container
        run: sudo docker rm -f devopes-ci-cd-container || true
      - name: Run Docker Container
        run: sudo docker run -d -p 3000:3000 --name devopes-ci-cd-container bilanox/devopes-ci-cd
